import Image from "next/image"
import Link from "next/link"
import { CircleDot, Shield } from "lucide-react"
import styles from "@/components/marketing/marketing.module.css"
export const metadata = { title: "Sports Programs for Kids & Schools | KoraKickz", description: "Explore soccer, basketball, and non-contact martial arts for schools, plus weekend soccer classes in Queens for ages 2–5." }
export default function SportsPage(){return <main className={styles.site}>
  <header className={styles.pageIntro}><div><p className={styles.eyebrow}>SPORTS PROGRAMS</p><h1>More sports.<br />More ways to grow.</h1><p>Discover a new interest, build confidence, and keep moving. Our programs adapt to each group’s age and experience.</p></div></header>
  <section className={`${styles.section} ${styles.storyGrid}`} id="soccer"><div className={styles.storyPhoto}><Image src="/photos/william.jpeg" alt="William smiling during a KoraKickz class" fill priority sizes="(max-width: 700px) 100vw, 45vw" style={{objectFit:"cover",objectPosition:"center 42%"}} /></div><div><span className={styles.badge}>School programs + weekend classes</span><h2>Soccer</h2><p className={styles.intro}>Playful games and age-appropriate activities introduce dribbling, passing, shooting, and teamwork. Children develop balance, coordination, and confidence as they learn.</p><p className={styles.intro}>Weekend soccer in Queens is open to ages 2–5, with classes in Astoria. School sessions are tailored to your students.</p><div className={styles.actions}><Link className={styles.primary} href="/soccer">Explore Soccer</Link><Link className={styles.secondary} href="/for-schools">For Schools</Link></div></div></section>
  <div className={styles.benefitSection}><section className={styles.section}><div className={styles.galleryGrid}>
    <article className={styles.sportCard} id="basketball"><span className={styles.icon}><CircleDot aria-hidden="true" /></span><h2 style={{marginTop:24}}>Basketball</h2><span className={styles.badge}>Available for schools · Weekend classes coming soon</span><p>From first bounces to team challenges, basketball helps students develop hand-eye coordination, ball control, and communication. Activities adapt to your students’ ages and abilities.</p><Link className={styles.cardLink} href="/for-schools#demo">Bring Basketball to Your School ↗</Link></article>
    <article className={styles.sportCard} id="martial-arts"><span className={styles.icon}><Shield aria-hidden="true" /></span><h2 style={{marginTop:24}}>Non-Contact Martial Arts</h2><span className={styles.badge}>Available for schools · Weekend classes coming soon</span><p>MMA, boxing, and wrestling fundamentals taught through non-contact activities—no sparring or fighting. Students practice movement, balance, self-control, and self-defense foundations in a supportive environment.</p><p style={{marginTop:16}}>An exciting option for older students and a fresh addition to your school’s enrichment offerings.</p><Link className={styles.cardLink} href="/for-schools#demo">Explore a School Program ↗</Link></article>
  </div></section></div>
  <section className={styles.section}><h2>One program. A world of possibilities.</h2><p className={styles.intro}>Soccer one month, basketball the next, or a new introduction to non-contact martial arts. We work with schools to build a schedule around their students, space, and budget.</p><Link className={styles.primary} href="/for-schools#demo">Request a Free School Demo</Link></section>
</main>}
